stages:
  - test

phpunit:
  image: "jegramos/webkit-php:v1.0"
  stage: test
  before_script:
    - echo "$WEBKIT_TESTING_ENV" > ".env.testing"
    - echo "Created .env.testing"
    - ls -lha
    - composer install
    - echo "Composer install completed"
  script:
    - php artisan test
