services:
  # The Laravel API application
  app:
    image: jegramos/webkit-api:latest
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_api'
    networks:
      - app-network
    ports:
      - '80:8080'
      - '443:8443'
    profiles: ['app']

  # Laravel Queue Container
  queue:
    image: jegramos/webkit-api:latest
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_queue'
    command: [
      'php',
      '/var/www/html/artisan',
      'queue:work',
      '--queue=otp,emails,dev_alerts,default',
      '--tries=3',
      '--sleep=3'
    ]
    networks:
      - app-network
    profiles: ['app']

  # Dedicated Container for Scheduled tasks
  tasks:
    image: jegramos/webkit-api:latest
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_tasks'
    command: ['php', '/var/www/html/artisan', 'schedule:work']
    networks:
      - app-network
    profiles: ['app']

  # Main Database
  db:
    image: mysql:8.1.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    profiles: [ 'store' ]
    # ports:
    #  - '3306:3306'

  # Cache Database
  cache-store:
    image: redis:7.2.1-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: cache-store-vol
        target: /data
    networks:
      - app-network
    profiles: [ 'store' ]
    #ports:
    #  - '6379:6379'

networks:
  app-network:
    driver: bridge

volumes:
  db-vol:
  cache-store-vol:
