services:

  # The Laravel API application
  app:
    build: .
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_api'
    depends_on:
      - db
      - cache-store
    networks:
      - app-network
    ports:
      - '80:8080'
      - '443:8443'

  # Laravel Queue Container
  queue:
    build: .
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_queue'
    command: [
      'php',
      '/var/www/html/artisan',
      'queue:work',
      '--queue=otp,emails,dev_alerts,default',
      '--tries=3',
      '--sleep=3'
    ]
    networks:
      - app-network
    depends_on:
      - db
      - cache-store

  # Dedicated Container for Scheduled tasks
  tasks:
    build: .
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: 'app_tasks'
    command: ['php', '/var/www/html/artisan', 'schedule:work']
    networks:
      - app-network

  # Main Database
  db:
    image: mysql:8.1.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '6000:3306'
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  # Cache Database
  cache-store:
    image: redis:7.2.1-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: cache-store-vol
        target: /data
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-vol:
  cache-store-vol:
